// Generated by gencpp from file metal_detector_msgs/SetCoilsZeroResponse.msg
// DO NOT EDIT!


#ifndef METAL_DETECTOR_MSGS_MESSAGE_SETCOILSZERORESPONSE_H
#define METAL_DETECTOR_MSGS_MESSAGE_SETCOILSZERORESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace metal_detector_msgs
{
template <class ContainerAllocator>
struct SetCoilsZeroResponse_
{
  typedef SetCoilsZeroResponse_<ContainerAllocator> Type;

  SetCoilsZeroResponse_()
    : success(false)
    , status_message()  {
    }
  SetCoilsZeroResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , status_message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _status_message_type;
  _status_message_type status_message;




  typedef boost::shared_ptr< ::metal_detector_msgs::SetCoilsZeroResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::metal_detector_msgs::SetCoilsZeroResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetCoilsZeroResponse_

typedef ::metal_detector_msgs::SetCoilsZeroResponse_<std::allocator<void> > SetCoilsZeroResponse;

typedef boost::shared_ptr< ::metal_detector_msgs::SetCoilsZeroResponse > SetCoilsZeroResponsePtr;
typedef boost::shared_ptr< ::metal_detector_msgs::SetCoilsZeroResponse const> SetCoilsZeroResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::metal_detector_msgs::SetCoilsZeroResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::metal_detector_msgs::SetCoilsZeroResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace metal_detector_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'metal_detector_msgs': ['/home/zakaria/hratc2017_workspace/src/metal_detector_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::metal_detector_msgs::SetCoilsZeroResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::metal_detector_msgs::SetCoilsZeroResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::metal_detector_msgs::SetCoilsZeroResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::metal_detector_msgs::SetCoilsZeroResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::metal_detector_msgs::SetCoilsZeroResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::metal_detector_msgs::SetCoilsZeroResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::metal_detector_msgs::SetCoilsZeroResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2ec6f3eff0161f4257b808b12bc830c2";
  }

  static const char* value(const ::metal_detector_msgs::SetCoilsZeroResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2ec6f3eff0161f42ULL;
  static const uint64_t static_value2 = 0x57b808b12bc830c2ULL;
};

template<class ContainerAllocator>
struct DataType< ::metal_detector_msgs::SetCoilsZeroResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "metal_detector_msgs/SetCoilsZeroResponse";
  }

  static const char* value(const ::metal_detector_msgs::SetCoilsZeroResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::metal_detector_msgs::SetCoilsZeroResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n\
string status_message\n\
\n\
";
  }

  static const char* value(const ::metal_detector_msgs::SetCoilsZeroResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::metal_detector_msgs::SetCoilsZeroResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.status_message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetCoilsZeroResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::metal_detector_msgs::SetCoilsZeroResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::metal_detector_msgs::SetCoilsZeroResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "status_message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.status_message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // METAL_DETECTOR_MSGS_MESSAGE_SETCOILSZERORESPONSE_H
